### ISSUE TITLE
ramification of the armature

### ISSUE THREAD

**Issue by ealfonsov89** [abpy/improved-sapling-tree-generator#1]
Hello, there is a feature that I think is missing, the depth of ramification of the armature, this would optimize models for use in video games

**Comment by abpy** [comment]
Thank you for your feedback, I appreciate it.
By ramification I'm guessing you mean reducing the number of bones in each branch. I agree, the trees have too many bones in the armature. Perhaps if there was 1 bone per stem up to a limited number of levels. I will look into it but It may be difficult to change.

**Comment by ealfonsov89** [comment]
i would try to do it, but for now i am very busy, if i do something y would make you know.

**Comment by abpy** [comment]
I dug into the code a bit and found the armature uses bone envelopes for binding. So if bones were removed the bezier points wouldn't be attached. It can't be done with curves, but it could be done with a mesh.
I intend to add meshing eventually, but i'm waiting to see if the new skin modifier will work
https://developer.blender.org/D1465

**Comment by ealfonsov89** [comment]
Hi, can you use the sum of the weight maps of childrens?

2015-09-27 11:55 GMT-07:00 Aaron notifications@github.com:

**Comment by ealfonsov89** [comment]
i made several experiments merging bones, it could be a starting point

2015-09-28 6:11 GMT-07:00 Ernesto Alfonso ealfonsov89@gmail.com:

**Comment by ealfonsov89** [comment]
if you get all bones that have only one child and merge?

2015-09-28 9:18 GMT-07:00 Ernesto Alfonso ealfonsov89@gmail.com:
