### ISSUE TITLE
add on runs very slow to me

### ISSUE THREAD

**Issue by manuvlad** [abpy/improved-sapling-tree-generator#10]
I have an 2011 iMac i5 with 8GB of ram in the office. And a i7 4930k (6 cores and 12 threads), with 32GB of ram and a GTX 980 ti in my home. The add on works very smoothly in the imac, but extremely slow in my very capable PC with the same tree assets. 

Someone else has this issue?

Thanks in advance.

**Comment by abpy** [comment]
I don't know why it would be slow on any particular computer, I've only tested on mac. But it is only single threaded so more cores wont help with trees. Make sure the preset is the same and "limit import" is off.

**Comment by manuvlad** [comment]
Thank you for your replay, man. "Limit import" was marked as "on". It is faster than before now.
