### ISSUE TITLE
Top branch

### ISSUE THREAD

**Issue by mbbmbbmm** [abpy/improved-sapling-tree-generator#11]
Hey, great job! Is there an option to turn off that top branch sitting directly on top of the stem? The old sapling didn't have it and I think sometimes it's useful but then sometimes it's not. Thanks!

**Comment by abpy** [comment]
Thats true, there may be some cases where branches at the tip may not be what you want but for most trees they're more realistic, I'll see about adding an option to turn them off.

**Comment by mbbmbbmm** [comment]
Yes, they are more realistic, I agree. I was actually experimenting with stylized/abstract trees when I felt the need to turn it off. Thank you for looking into it.
Another idea would be to have a smooth transition from the trunk (no gap) and the ability to control the length of the top branch. But I'm not sure if that would be worth the hassle? Anyway, thanks again!

**Comment by abpy** [comment]
added

**Comment by mbbmbbmm** [comment]
Awesome! Thank you
