### ISSUE TITLE
Rotate world

### ISSUE THREAD

**Issue by monatsend** [abpy/improved-sapling-tree-generator#15]
Hi, 
I love this addon and i like to create with it branches as well. 
but to have good results i need to rotate the the whole Tree 90 deg in x or y but with gravity still pointing upwards.  so leafes and branches bend and point up 
is such a thing possible?

**Comment by abpy** [comment]
If you are trying to make individual branches not attached to a trunk I would suggest making a tree with just a few branches and deleting the trunk. If you want the first level(trunk) to use as a branch, I may make a change that might do what you want.

**Comment by monatsend** [comment]
Sorry for the late answer. 
Thats a very good idea. I try if I can create good results with it 
Thanks for your quick response.
