### ISSUE TITLE
leaf object

### ISSUE THREAD

**Issue by FarcryLi** [abpy/improved-sapling-tree-generator#16]
First,Thanks for your addon!I love it!
I try to replace leaves with crossed planes(one object,origin in the buttom of plane center),and I chooes DupliFaces but nothing happened only some random rectangular in the branch , also show leaf was checked.
How to use leaf object?

**Comment by abpy** [comment]
Make sure you choose the object in the 'Leaf Object:' drop-down menu.
It should parent it to the tree curves object. Also check that 'leaves' and 'leaf scale' are not zero.
