### ISSUE TITLE
DupliFaces leaves after tree creation.

### ISSUE THREAD

**Issue by TheRuleOfMike** [abpy/improved-sapling-tree-generator#17]
Hello:) As usual - thank you for your amazing work on this powerful add-on.

I do however have a big problem with the leaves when I use an object (dupli faces). After the tree creation I would like to separate the generated leaves in to a full object (not just the faces which from the duplis are created but as a complete mesh - similar to what would happen if you'd convert a particle system to be "real"). And here is the problem - from the Blender UI perspective the dupli objects seem to not exist. I guess there is a particle system in the background (because adding a new one makes the sampling duplis disappear) however there is no way to fiddle with the particle system through the UI or the addon menus before completing the creation of the sapling tree. The outliner doesn't register any particle system on the leaves and yet it is there.

Why is it a problem? Well, with this state of things the baking option is broken to the point of simply crashing blender. What I want to do is bake (to a plane - normal, specular, smoothness, albedo etc.) a small branch of an alien tree with large leaves I made, to then use it as a basis for a more detailed/low-poly leaf system for the final tree. Do you know any solution for this? Or can you direct me to a way of "materializing" the particle system behind the dupli faces?
![ciennik soczewkowy drzewo](https://cloud.githubusercontent.com/assets/19647983/24654792/991b4370-193b-11e7-8d29-254ad99fe8e9.png)

**Comment by abpy** [comment]
The dupli faces option uses blenders [DupliFaces](https://docs.blender.org/manual/en/dev/editors/3dview/object/properties/duplication/duplifaces.html). There is no underlying particle system. These can be converted into objects by using Object>Apply>Make Duplicates Real. Then they can be joined into a single object.
![screen shot 2017-04-04 at 2 36 19 pm](https://cloud.githubusercontent.com/assets/5454400/24673019/cb956250-1944-11e7-9b5f-560d551081c7.png)

**Comment by TheRuleOfMike** [comment]
Fantastic! This makes everything clear and indeed worked perfectly. Thank you for the fast answer.

**Comment by fhcampbell** [comment]
The sapling tree generator isn't working like previously.  The menu (geometry, etc) is all greyed out. Are there any suggestions what caused that? 
![screen shot 2018-03-26 at 8 31 41 pm](https://user-images.githubusercontent.com/4656464/37925860-fb7b662c-3135-11e8-9610-e81646388059.png)

**Comment by abpy** [comment]
You should just open a new issue.

**Comment by fhcampbell** [comment]
i tried.
i tested it in diff games too
