### ISSUE TITLE
Sapling: Add Tree settings will not reappear after clicking on another menu

### ISSUE THREAD

**Issue by nataliadalomba** [abpy/improved-sapling-tree-generator#19]
I'm sorry if this issue has already been reported, but it's a bit of a pain. I heard this is standard Blender behavior and maybe there's no way around it...but if it's possible, that would make this plugin perfect!!

I guess for now we just have to reallyyy make sure we're happy with our tree before we click out of it. Thanks!

**Comment by abpy** [comment]
see latest commit

**Comment by Copperplate** [comment]
Just had to say this addon is incredible. In just a few clicks, I can get an amazing tree with beautiful animation (including leaf animation!!). I'm not sure if Natalia was referring to the fact that clicking on (and translating) another object in the scene will cause the Tool Shelf settings to disappear.

I believe that behavior is a limitation of Blender's code. It would be neat if selecting a pre-existing tree enabled you to edit its individual settings, but that would require some way of locally storing its data and setting those properties to be the ones listed in the Tools panel. If the storage of data could be overcome by somehow automatically storing the settings for each tree in one (or many) text files, then a menu option could be added, such as: Select tree, press "W", and select "Edit Tree". This would then activate the Sapling Add Tree settings in the Tools panel, and would populate the values with those stored in the text file, based on the the tree's name. Hmm... easy to write, but probably morbidly difficult to implement from a programmer's view! :-)

Anyways, thanks Aaron for developing this awesome tool! :1st_place_medal:
