### ISSUE TITLE
sapling-tree-generator menu is unresponsive after curve-add

### ISSUE THREAD

**Issue by fhcampbell** [abpy/improved-sapling-tree-generator#20]
Greyed.  See ?
![screen shot 2018-03-26 at 8 31 41 pm](https://user-images.githubusercontent.com/4656464/37927404-45e016fa-313a-11e8-8707-af49ff794d1b.png)

Happened first time, only today.
Tested the existing game files where it worked (ie., tried to add a new tree) and then empty file: Each time, the menu is inaccessbile and always grey.

Did something go missing in the source??

**Comment by Copperplate** [comment]
Hi fhcampbell, go to File > User Preferences > Editing, and make sure "Global Undo" is checked. Sometimes certain addons can disable this at random and cause the panel to gray out.

**Comment by fhcampbell** [comment]
It WORKED Cooperplate!!  

High 5!!!
![screen shot 2018-03-26 at 9 46 20 pm](https://user-images.githubusercontent.com/4656464/37929067-2ea8a6aa-313f-11e8-94d3-e006d53c9218.png)
Thank you so super much.

**Comment by Copperplate** [comment]
That's great! You're very welcome. I had the same problem caused from the Tool+ (T+ Curves) addon that would repeatedly trigger that glitch (I couldn't figure out why Blender had grayed out the options to modify a newly added circle). Remember to also hit "Save User Settings" in User Preferences so it will remember your selection (at least until the next glitch). :-)

**Comment by abpy** [comment]
Thank you Copperplate, for helping. I would not have known that.

**Comment by Copperplate** [comment]
You are welcome, Aaron. Thank you for all your hard work in developing this excellent addon. :-)
