### ISSUE TITLE
Material place holder for branch levels

### ISSUE THREAD

**Issue by dstrinholm** [abpy/improved-sapling-tree-generator#21]
Great add-on!

Would there be a way to easily add a material place holder for each branch level?

Example - I want to add a large scale bark texture to the trunk and main branch limbs, I then want to add a medium scale bark texture to the second level of branches and finally just a grey/brown color to the third level (twigs) of branches.

Having a material setup for each level of branches, by defalut, would make this easy to do. Without material place holders I have to select individual curves to assign the different materials. This is ok for trunk and main branch limbs but gets quite time consuming for all the smaller branches at levels 2 and 3. The material place holders don't need to be anything more than just a material name assigned to the branch levels, so you can select the branches by material.

Thanks for all your work on this! Especially dupliverts for leaf objects!! Much appreciated!

**Comment by abpy** [comment]
Good Idea, seems simple enough, I may work on it soon.

**Comment by abpy** [comment]
option for material slots added

**Comment by dstrinholm** [comment]
THANK YOU!! The option for the material slots is perfect and EXACTLY what I was hoping for! This will improve my workflow greatly. Thanks so much for all your great work!
