### ISSUE TITLE
[Q]Do you mind if i use the code save presets

### ISSUE THREAD

**Issue by schroef** [abpy/improved-sapling-tree-generator#22]
Hi there,

Im trying to make an add to the rigify addon so users can make presets of bone groups and load these with their own set of colors.

My question is, is it okay if i use the part of code where you save / load presets?

**Comment by abpy** [comment]
Yes, you may use my code as reference and copy/paste. I can not guarantee if it's correct or will work for your addon.

**Comment by schroef** [comment]
Yeah i noticed, its very hard to do, you have all settings as attributes and than it adds them quite easy. I used it in a separate operator as a test but when i call that, that operator also gets added to the preset. I looked at the standard preset adding method, but i cant figure out how to give values there, i needs a set but i dont know how i can add that in a proper way?
