### ISSUE TITLE
[B]Presets are now saved to the user presets folder

### ISSUE THREAD

**Issue by schroef** [abpy/improved-sapling-tree-generator#23]
I noticed in your updates that presets are now save to the user preset folder. Yet this isnt the case if the addon is installed within the Blender app, like the prior version.

I test this by adding this 3.1 version on OSX in the blender.app>scripts>addons

When i than save a preset it is saved to scripts>presets>operator>add_curve_sapling_3 just like before. Why not add a custom folder within the addon folder and save them there?

**Comment by abpy** [comment]
I don't know if there is a blender standard for that, but I think the scripts folder in user/library is meant for addons to use. Are you having problems saving or accessing presets?

**Comment by schroef** [comment]
No i dont have issues, perhaps add the sapling presets to the main folder instead of nested under the operator, though it is an operator ofcourse.
