### ISSUE TITLE
Bake animation

### ISSUE THREAD

**Issue by mistajuliax** [abpy/improved-sapling-tree-generator#24]
Is there a way to bake animation ?

**Comment by abpy** [comment]
Yes, the animation is made with f-curve modifiers. These can be baked to keyframes in blender.

**Comment by mistajuliax** [comment]
Hi, thanks for replying. I'm not really familiar with animation in blender. I need to open graph editor and ceck out f-curves with my tree selected ? But i have no curves ine graph editor ... What are the steps to follow please ?
