### ISSUE TITLE
Simple update may be needed.

### ISSUE THREAD

**Issue by tom-henrich** [abpy/improved-sapling-tree-generator#28]
Hey there!

I just wanted to say thanks for all the work you are putting into this. It has helped me tremendously in porting to 2.8. I have been skimming through the code to work with my addon script and noticed that for the **_'wind'_** property, it may have been overlooked (converting it to a keyword argument). See below:

![image](https://user-images.githubusercontent.com/32705716/66750033-59f15900-ee59-11e9-8f02-47be774c5398.png)

Obviously not a huge deal but figured it was worth mentioning for future iterations!

EDIT: Hey sorry, I don't mean to pile on but figured since I was going through the code line by line for my own code I would keep tabs on anything I spotted: In  the ___init__.py_ file, when you are unregistering your menus, you have an '.append' where it should be '**.remove**'. See below:

![image](https://user-images.githubusercontent.com/32705716/66762339-cf6a2300-ee73-11e9-9d6e-56ecaba4b5fa.png)

**Comment by abpy** [comment]
Fixed
