### ISSUE TITLE
Wrong Leaf Object Name with Prune activated

### ISSUE THREAD

**Issue by ControllerArts** [abpy/improved-sapling-tree-generator#29]
The option Prune creates an extra object (envelope) making the name of the objects not corresponding to the actual object. The position of the object name is offsetted by one.

![image](https://user-images.githubusercontent.com/20363585/66780158-854e6500-eea6-11e9-831f-810a7bad2e9b.png)

**Comment by abpy** [comment]
I was able to reproduce this, not sure whats causing it but i may look into it.

**Comment by abpy** [comment]
latest commit should help
