### ISSUE TITLE
Loop animation in BGE

### ISSUE THREAD

**Issue by alabd14313** [abpy/improved-sapling-tree-generator#3]
Hi!
How I loop animation for using in BGE?

**Comment by abpy** [comment]
It's not possible now. I'll look into it.
Approximately how many frames would you want to loop?

**Comment by alabd14313** [comment]
For optimization and natural wind movement it's better to be between 120 to 250.
Please duplicate it for 10 trees (and different start and end frames for randomness) and compare performance. What is your idea? What if different trees (performance)?
Here is a simple example:
http://www.mediafire.com/download/sae4dx5x4c21odo/tree.blend

**Comment by abpy** [comment]
Recent changes include looping for animations.

**Comment by alabd14313** [comment]
Thanks! It's very cool. Hope not to feel tired!
Edited: Continues moved to new issue to close this issue.
