### ISSUE TITLE
Wrong resolution for last-level branches

### ISSUE THREAD

**Issue by khalv** [abpy/improved-sapling-tree-generator#30]
Some splits at the end of branches appear to be unaffected by the resolution settings specified in the splitting settings. This is quite inconvenient when trying to make low-poly trees. 

![TreeGen](https://user-images.githubusercontent.com/16840336/80892359-b159f800-8cc9-11ea-9f19-d73727364881.jpg)

**Comment by abpy** [comment]
I confirmed this is an issue. I'll fix it shortly

**Comment by abpy** [comment]
fixed
