### ISSUE TITLE
Likely future

### ISSUE THREAD

**Issue by alabd14313** [abpy/improved-sapling-tree-generator#4]
Hello @abpy !
I show BGE work flow in this clip:
http://www.aparat.com/v/n93le

> 1- Clear parent tree from treearm 
> 2- Clear parent leaves from tree
> 3- Convert tree and leaves to mesh (leaves conversion is optional)(Texturing and other stuffs can be now or later)
> 4- Parent leaves to tree 
> 5- Parent tree to treearm with automatic weight (automatic weight is necessary and if we parent with object and keep transform and then add armature modifier to tree, then we have to set to bone envelop in modifier and not work on BGE)
> 6- Add armature modifier to leaves (if leaves converted to mesh manually)
> 7- In this step, if we add logic bricks to treearm, leaves animation works in render mode and don't work on BGE.
> 8- The solution is change the parent of the leaves from tree to treearm.

So this work flow can be reduced if there is an option in menu for auto conversion tree to mesh.

Current state of tree gen is random seed based. How we can have more control on tree specifications, like this (as inspiration not adoption):
https://www.youtube.com/watch?v=LrGt27UIPxk

There are some easy tricks like this:
http://www.aparat.com/v/vYlzQ
But how implement armatures and leaves!!!

Future plans can be:

> 1- Wind direction (Wind effect on leaves and thin branches and subbranches is greater than thick branches and trunk and main brancjes, so armature animation must be differ)
> 2- Underwater vegetation physics (slow movement)
> 3- Growth improvements (This script can be useful as inspiration and ideas https://github.com/Tlousky/ivy_growth_animator)
> 4- Animation optimization for BGE (more or less like current control on  wind speed and etc in menu)
> 5- Grass gen (optimized armature and size and ... for render and BGE) and grass growth (more or less In current state can be done but with  time-consuming and grass textures can insert on leaves but for BGE this is resource-consuming because of branches overhead)
> 6- Change specification any time (Current state is first produce and use for all time without change parameters. It is better to be: first produce and change parameters and optimize any time) -> armatures and leaves and vertices is a challenge.

Finally some gnarled trees. Do you have any idea?
![gnarled-tree-roots-and-trunk-by-lake-mendocino](https://cloud.githubusercontent.com/assets/14325605/11089782/c9245558-8881-11e5-9e44-664d00a3a225.jpg)
![149921_ac75f7b429ad3ab7a1a5433e35c8e3a1_large](https://cloud.githubusercontent.com/assets/14325605/11089786/d3bf6f34-8881-11e5-9e06-e6cf8a1b84df.jpg)
![gnarled-tree-wales](https://cloud.githubusercontent.com/assets/14325605/11089787/d54090ae-8881-11e5-9472-a7c4d57ff0dc.jpg)
and fantasy persian tree (artist: Mahmoud Farshchian):
![mahmood farshchian](https://cloud.githubusercontent.com/assets/14325605/11089806/047d3fc0-8882-11e5-9bdd-ba6c0aeb2c9d.gif)

**Comment by abpy** [comment]
Maybe a script could be written to convert a tree for BGE.
I already have some animation changes in the works.
The gnarled trees you show are probably best done manually and sculpted, also using the armature to pose the tree.

**Comment by abpy** [comment]
here is a script to convert a tree to work in bge.
[tree_to_mesh.txt](https://github.com/abpy/improved-sapling-tree-generator/files/43428/tree_to_mesh.txt)
1, open in blender text editor
2, select armature of tree
3, run script

it assumes that the tree has leaves

**Comment by alabd14313** [comment]
I don’t have anything to give in return.
Only, Thank you!
