### ISSUE TITLE
Impossible to preview armature animation?

### ISSUE THREAD

**Issue by Copperplate** [abpy/improved-sapling-tree-generator#5]
Hello friends,

First let me state this is a phenomenal add-on, and your work on improving it is definitely paying off.

I would like to bring an issue to your attention; perhaps it will help the developers here.
When trying to use an animated armature for my plant (which has 3 levels and 21, 21, 14, 1 for curve resolution) the "Use Armature" "Armature Animation" and "Leaf Animation" check boxes all take 30+ seconds to update after initiating, then, trying to preview the animation is impossible. 

Now I understand with so much curve resolution this would be understandable. However, all I need to see is the armature itself animated, nothing else. This, unfortunately, is impossible to achieve at present. 

At some point in the old sapling add-on, you were able to preview your wind speed changes, etc. thanks to the fact that ONLY the armature was animated while the add-on was still active in the toolshelf. However, in the new sapling add-on, the curve's armature modifier also becomes activated by default, forcing the framerate to drop to zero (or simply freeze). I've tried disabling the armature modifier, hoping to preview only the armature animation, but unfortunately, as long as the add-on is active, the same problem persists.

As soon as the add-on is no longer active, however, you can happily disable the armature modifier on the plant and watch the motion of just the armature with relative ease.I've included my preset file which shows the issue. I've also included my oat husk primitive which serves as the dupliface object. While this issue is visible even without the primitive, I've noticed you can't adjust most of the settings in the Leaves tab if "Leaves" is set to -1 (not sure if this is a bug or intended, as I'm still learning this add-on). One other small thing I noticed is that some (not all) of the  stems appear to be partially severed (cracked) just before the tips, and in general, are too pointy when cap ends is selected. I'm not sure how to avoid these other smaller issues.

Many thanks for reading this and for all your hard work!

~Adam Janz
P.S. Please remember to disable "Limit Import" when you load my preset in the starter file, as it has 3 levels.
[Oat_husk_starter_file.zip](https://github.com/abpy/improved-sapling-tree-generator/files/57374/Oat_husk_starter_file.zip)

**Comment by abpy** [comment]
hi, 

You're right, it is a LOT faster to play the animation with only the armature. I'll add an option to turn off the modifier to preview the motion.

If you enable auto curve handles you can set the resolution a lot lower

The cracks are the seams between separate stem curves, and close tip just sets the branch tip radius to zero, I would leave it off for this plant.

**Comment by Copperplate** [comment]
Thank you so much! That would be fantastic.

Thank you for your tips as well. The cracks can be remedied somewhat by scaling one of the handles, as seen in the attached photos.

Have a great day!
~Adam
![crack](https://cloud.githubusercontent.com/assets/16230743/11755380/948e4ad0-a017-11e5-9128-e0a172a1a111.jpg)
![crack_handle scaled](https://cloud.githubusercontent.com/assets/16230743/11755384/9beb2424-a017-11e5-8350-72785aac6a9c.jpg)
