### ISSUE TITLE
Exception when increasing Radius Scale Variation

### ISSUE THREAD

**Issue by DailyFrankPeter** [abpy/improved-sapling-tree-generator#7]
Hi, 

Great addon. Thanks for picking up the development of this. I'm still learning my way around but it looks pretty potent. 

I ran into an error and thought you might find this stacktrace useful:

![tree bug](https://cloud.githubusercontent.com/assets/13888557/13354388/0677f3f2-dc9b-11e5-9d4e-f207f12da866.jpg)

**Comment by abpy** [comment]
Thank you, This was difficult to reproduce but I think I found it. Though this is a setting that should be left at small numbers.

**Comment by DailyFrankPeter** [comment]
Thanks, too. I will try to provide a better repro recipe next time, so as to not waste anyone's time!
